/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Proj model module.
 * @module model/Proj
 * @version 1.0.0
 */
class Proj {
    /**
     * Constructs a new <code>Proj</code>.
     * @alias module:model/Proj
     * @param title {String} 
     * @param image {String} 
     * @param _abstract {String} 
     */
    constructor(title, image, _abstract) { 
        
        Proj.initialize(this, title, image, _abstract);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, image, _abstract) { 
        obj['title'] = title;
        obj['image'] = image;
        obj['abstract'] = _abstract;
    }

    /**
     * Constructs a <code>Proj</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Proj} obj Optional instance to populate.
     * @return {module:model/Proj} The populated <code>Proj</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Proj();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('abstract')) {
                obj['abstract'] = ApiClient.convertToType(data['abstract'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Proj.prototype['_id'] = undefined;

/**
 * @member {String} title
 */
Proj.prototype['title'] = undefined;

/**
 * @member {String} image
 */
Proj.prototype['image'] = undefined;

/**
 * @member {String} abstract
 */
Proj.prototype['abstract'] = undefined;






export default Proj;

